# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b999cd693a3e3997df20283fde608f390f3c26ff5aae289c72a71e62e75d0e2488aed1210938949a0f67207327180fb972871168463875357288e218288dc843

test:
  secret_key_base: 7ab901a3bb419ecc76b1a7b0fe7c911db0e2cfee34ead10e8dbbe3b761c3f0fd901bcf881da80bf79462c53fd17d31619001c2d37ef8fd697764bdeacc9b1a63

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
